export const env = {
  DEV: import.meta.env.DEV,
  VITE_PAYFAST_MERCHANT_ID: import.meta.env.VITE_PAYFAST_MERCHANT_ID,
  VITE_PAYFAST_MERCHANT_KEY: import.meta.env.VITE_PAYFAST_MERCHANT_KEY,
  VITE_PAYFAST_SANDBOX_MERCHANT_ID: import.meta.env.VITE_PAYFAST_SANDBOX_MERCHANT_ID,
  VITE_PAYFAST_SANDBOX_MERCHANT_KEY: import.meta.env.VITE_PAYFAST_SANDBOX_MERCHANT_KEY
} as const;
