/**
 * Backfill province on comparable_sales based on suburb name.
 * Run once: npx tsx scripts/backfill-province.ts
 */

import pg from "pg";
import * as dotenv from "dotenv";
dotenv.config();

const PROVINCE_MAP: Record<string, string> = {
  // Western Cape
  "AIRLIE": "Western Cape",
  "ALPHEN": "Western Cape",
  "ATHLONE": "Western Cape",
  "BANTRY BAY": "Western Cape",
  "BELLE CONSTANTIA": "Western Cape",
  "BELLVILLE": "Western Cape",
  "BELLVILLE SOUTH": "Western Cape",
  "BEL OMBRE": "Western Cape",
  "BERGVLIET": "Western Cape",
  "BISHOPSCOURT": "Western Cape",
  "BLOUBERG RISE": "Western Cape",
  "BLUE DOWNS": "Western Cape",
  "BO OAKDALE": "Western Cape",
  "BOSTON": "Western Cape",
  "BRIERSWOOD ESTATE": "Western Cape",
  "CAMPS BAY": "Western Cape",
  "CAPE TOWN": "Western Cape",
  "CAPE TOWN CITY CENTRE": "Western Cape",
  "CAPE TOWN HARBOUR": "Western Cape",
  "CAPRICORN": "Western Cape",
  "CLAREMONT CAPE": "Western Cape",
  "CLIFTON": "Western Cape",
  "CONSTANTIA": "Western Cape",
  "CONSTANTIA HEIGHTS": "Western Cape",
  "CROFTERS VALLEY": "Western Cape",
  "EDGEMEAD": "Western Cape",
  "EERSTERIVIER": "Western Cape",
  "FERNWOOD ESTATE": "Western Cape",
  "FIR GROVE": "Western Cape",
  "FISH HOEK": "Western Cape",
  "FRESNAYE": "Western Cape",
  "GARDENS": "Western Cape",
  "GLENCAIRN": "Western Cape",
  "GLENCAIRN HEIGHTS": "Western Cape",
  "GLENTANA": "Western Cape",
  "GOLDEN ACRE": "Western Cape",
  "GREEN POINT": "Western Cape",
  "HARFIELD VILLAGE": "Western Cape",
  "HAZENDAL": "Western Cape",
  "HEIDEVELD": "Western Cape",
  "HELDERBERG VILLAGE": "Western Cape",
  "HELDERVUE": "Western Cape",
  "HIGHOVALE": "Western Cape",
  "HIGGOVALE": "Western Cape",
  "HOEKWIL": "Western Cape",
  "HOUT BAY": "Western Cape",
  "HOUT BAY BEACHFRONT": "Western Cape",
  "KALK BAY": "Western Cape",
  "KENILWORTH": "Western Cape",
  "KLEINVLEI": "Western Cape",
  "KRAAIFONTEIN": "Western Cape",
  "LAND EN ZEEZICHT": "Western Cape",
  "LANGEBERG RIDGE": "Western Cape",
  "MAITLAND GARDEN VILLAGE": "Western Cape",
  "MANENBERG": "Western Cape",
  "MELKBOSCH STRAND": "Western Cape",
  "MILNERTON": "Western Cape",
  "MONTE VISTA": "Western Cape",
  "MOWBRAY": "Western Cape",
  "MUIZENBERG": "Western Cape",
  "NDABENI": "Western Cape",
  "NEWLANDS CAPE": "Western Cape",
  "NOORDHAVEN": "Western Cape",
  "NOORDHOEK": "Western Cape",
  "NOVA CONSTANTIA": "Western Cape",
  "OBSERVATORY": "Western Cape",
  "ONRUSTRIVIER": "Western Cape",
  "ORANJEZICHT": "Western Cape",
  "OUTENIQUA STRAND": "Western Cape",
  "PANORAMA": "Western Cape",
  "PAREL VALLEI": "Western Cape",
  "PARKLANDS": "Western Cape",
  "PAROW": "Western Cape",
  "PEARL RISE": "Western Cape",
  "PENZANCE ESTATE": "Western Cape",
  "PINELANDS": "Western Cape",
  "PLATTEKLOOF": "Western Cape",
  "PLATTEKLOOF GLEN": "Western Cape",
  "PLETTENBERG BAY": "Western Cape",
  "PLUMSTEAD": "Western Cape",
  "ROGGEBAAI": "Western Cape",
  "RONDEBOSCH": "Western Cape",
  "ROSEBANK": "Western Cape",
  "SCHOTSCHEKLOOF": "Western Cape",
  "SCOTT ESTATE": "Western Cape",
  "SEA POINT EAST": "Western Cape",
  "SEA POINT WEST": "Western Cape",
  "SEDGEFIELD": "Western Cape",
  "SILVERHURST": "Western Cape",
  "SOMERSET RIDGE": "Western Cape",
  "SOMERSET WEST": "Western Cape",
  "SONNENDAL": "Western Cape",
  "STEENBRAS VIEW": "Western Cape",
  "STELLENBOSCH": "Western Cape",
  "STELLENBOSCH RD": "Western Cape",
  "ST JAMES": "Western Cape",
  "STONEHURST ESTATE": "Western Cape",
  "STONEY PLACE": "Western Cape",
  "STRAND": "Western Cape",
  "STRAND CENTRAL": "Western Cape",
  "STRAND NORTH": "Western Cape",
  "STRAND SOUTH": "Western Cape",
  "SUNNINGDALE": "Western Cape",
  "SUNSET BEACH": "Western Cape",
  "TABLE VIEW": "Western Cape",
  "TAMBOERSKLOOF": "Western Cape",
  "THE STRAND": "Western Cape",
  "THE VINES": "Western Cape",
  "UITZICHT": "Western Cape",
  "UNIVERSITY ESTATE": "Western Cape",
  "VERMONT": "Western Cape",
  "VIERLANDEN": "Western Cape",
  "VREDEHOEK": "Western Cape",
  "VREDELUST": "Western Cape",
  "WALMER ESTATE": "Western Cape",
  "WELGELEGEN": "Western Cape",
  "WEST BEACH": "Western Cape",
  "WESTLAKE": "Western Cape",
  "WESTRIDGE": "Western Cape",
  "WOODBRIDGE ISLAND": "Western Cape",
  "WOODSTOCK": "Western Cape",
  "WYNBERG": "Western Cape",
  "WYNBERG EXT 1": "Western Cape",
  "ZONNEBLOEM": "Western Cape",
  "AVONDALE": "Western Cape",
  "EDINBURGH": "Western Cape",
  "SANS SOUCI": "Western Cape",
  "SAN MICHEL": "Western Cape",

  // Gauteng
  "ARCADIA": "Gauteng",
  "AUCKLAND PARK": "Gauteng",
  "BARDENE": "Gauteng",
  "BARTLETT": "Gauteng",
  "BEDFORD GARDENS": "Gauteng",
  "BEDFORDVIEW": "Gauteng",
  "BERGBRON": "Gauteng",
  "BOSKRUIN": "Gauteng",
  "BRONBERG": "Gauteng",
  "BRONBERRIK": "Gauteng",
  "BRONKHORSTSPRUIT": "Gauteng",
  "BRYANSTON": "Gauteng",
  "CELTISDAL": "Gauteng",
  "CRAIGHALL PARK": "Gauteng",
  "DAINFERN": "Gauteng",
  "DELAREY": "Gauteng",
  "DIE HOEWES": "Gauteng",
  "DIE WINGERD": "Gauteng",
  "DISCOVERY": "Gauteng",
  "DORANDIA": "Gauteng",
  "DOUGLASDALE": "Gauteng",
  "DUNCANVILLE": "Gauteng",
  "DUXBERRY": "Gauteng",
  "ELARDUSPARK": "Gauteng",
  "ELDORAIGNE": "Gauteng",
  "EMMARENTIA": "Gauteng",
  "ERASMUS": "Gauteng",
  "FAERIE GLEN": "Gauteng",
  "FAIRLAND": "Gauteng",
  "FERNDALE": "Gauteng",
  "FLORAUNA": "Gauteng",
  "FLORIDA": "Gauteng",
  "FLORIDA GLEN": "Gauteng",
  "FLORIDA LAKE": "Gauteng",
  "FLORIDA NOORD": "Gauteng",
  "FLORIDA VIEW": "Gauteng",
  "FOURWAYS": "Gauteng",
  "GERDVIEW": "Gauteng",
  "GLENADRIENNE": "Gauteng",
  "GREENSIDE": "Gauteng",
  "GREENSIDE EAST": "Gauteng",
  "GREENSIDE EXT": "Gauteng",
  "GREENSTONE HILL": "Gauteng",
  "GRIMBEEKPARK": "Gauteng",
  "HENNOPSPARK": "Gauteng",
  "HEUWELOORD": "Gauteng",
  "HOUGHTON ESTATE": "Gauteng",
  "HURLINGHAM": "Gauteng",
  "ILLIONDALE": "Gauteng",
  "IMPALAPARK": "Gauteng",
  "JR (GAUTENG)": "Gauteng",
  "KENILWORTH PARK": "Gauteng",
  "KILLARNEY": "Gauteng",
  "KLIPKOP": "Gauteng",
  "LEEUHOF": "Gauteng",
  "MAGALIESSIG": "Gauteng",
  "MELVILLE": "Gauteng",
  "MIDSTREAM ESTATE": "Gauteng",
  "MONAVONI": "Gauteng",
  "MONTE SERENO": "Gauteng",
  "MORELETAPARK": "Gauteng",
  "MORNINGSIDE": "Gauteng",
  "MUCKLENEUK": "Gauteng",
  "NORTHCLIFF": "Gauteng",
  "NORTHWOLD": "Gauteng",
  "PARKHURST": "Gauteng",
  "PARKTOWN NORTH": "Gauteng",
  "PARKVIEW": "Gauteng",
  "PARKWOOD": "Gauteng",
  "PAULSHOF": "Gauteng",
  "PIERRE VAN RYNEVELD": "Gauteng",
  "PRETORIA NORTH": "Gauteng",
  "PRIMROSE": "Gauteng",
  "QUELLERINA": "Gauteng",
  "RANDPARKRIF": "Gauteng",
  "RAVENSWORTH ESTATE": "Gauteng",
  "RIETFONTEIN": "Gauteng",
  "RIVER CLUB": "Gauteng",
  "RIVERGLEN": "Gauteng",
  "RIVIERA (JHB)": "Gauteng",
  "ROOIHUISKRAAL": "Gauteng",
  "ROUKEN GLEN": "Gauteng",
  "ROUNDHAY": "Gauteng",
  "RUSTHOF": "Gauteng",
  "SAGEWOOD": "Gauteng",
  "SAXONWOLD": "Gauteng",
  "SOLHEIM": "Gauteng",
  "STRIJDOMPARK": "Gauteng",
  "STRUBENSVALLEI": "Gauteng",
  "STUARTS HILL": "Gauteng",
  "SUNDOWNER": "Gauteng",
  "SUNNYRIDGE": "Gauteng",
  "SUNNYROCK": "Gauteng",
  "SUNNYSIDE (PTA)": "Gauteng",
  "SYMHURST": "Gauteng",
  "TREVENNA": "Gauteng",
  "TROVATO": "Gauteng",
  "TWIN PALMS": "Gauteng",
  "VALHALLA": "Gauteng",
  "VANDERBIJL PARK SOUTH EAST NO 1": "Gauteng",
  "VANDERBIJL PARK SOUTH EAST NO 2": "Gauteng",
  "VANDERBIJL PARK SOUTH EAST NO 6": "Gauteng",
  "VANDERBIJL PARK SOUTH EAST NO 7": "Gauteng",
  "VEREENIGING": "Gauteng",
  "VICTORY PARK": "Gauteng",
  "WILGEHEUWEL": "Gauteng",
  "WILLOWILD": "Gauteng",
  "WILROPARK": "Gauteng",
  "WINDSOR PARK": "Gauteng",
  "WINDSOR PARK ESTATE": "Gauteng",
  "WITKOPPEN": "Gauteng",
  "WONDERBOOM SOUTH": "Gauteng",
  "WYNDOVER": "Gauteng",
  "ZOO PARK": "Gauteng",
  "BEVERLEY": "Gauteng",
  "BRIDGE WATER": "Gauteng",
  "DURMONTE": "Gauteng",
  "GOLIATH ESTATE": "Gauteng",
  "HELGARDA ESTATE": "Gauteng",
  "HELENA HEIGHTS": "Gauteng",
  "NORTHSHORE": "Gauteng",
  "STONEHENGE": "Gauteng",

  // KwaZulu-Natal
  "AMANZIMTOTI": "KwaZulu-Natal",
  "COWDRAY PARK": "KwaZulu-Natal",
  "COWIES HILL": "KwaZulu-Natal",
  "PINETOWN": "KwaZulu-Natal",
  "SCOTTSVILLE": "KwaZulu-Natal",
  "SEA VISTA": "KwaZulu-Natal",
  "WESTVILLE": "KwaZulu-Natal",

  // Eastern Cape
  "BEACON BAY": "Eastern Cape",
  "CAPE RD": "Eastern Cape",
  "FRAMESBY": "Eastern Cape",
  "KABEGA": "Eastern Cape",
  "MOUNT ROAD": "Eastern Cape",
  "NORTH END": "Eastern Cape",
  "PORT ELIZABETH CENTRAL": "Eastern Cape",
  "ST FRANCIS LINKS": "Eastern Cape",

  // Mpumalanga
  "NELSPRUIT": "Mpumalanga",
  "SONHEUWEL": "Mpumalanga",

  // Limpopo
  "HOEDSPRUIT": "Limpopo",
  "TZANEEN": "Limpopo",

  // North West
  "BAILLIE PARK": "North West",
  "POTCHEFSTROOM": "North West",

  // Free State
  "DENEYSVILLE": "Free State",
};

async function main() {
  const client = new pg.Client({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false },
  });
  await client.connect();

  // Run migration first
  await client.query(`
    ALTER TABLE comparable_sales ADD COLUMN IF NOT EXISTS province TEXT;
    CREATE INDEX IF NOT EXISTS comparable_sales_province_idx ON comparable_sales (province);
  `);
  console.log("Migration applied.");

  let updated = 0;
  let skipped = 0;

  for (const [suburb, province] of Object.entries(PROVINCE_MAP)) {
    const result = await client.query(
      `UPDATE comparable_sales SET province = $1 WHERE UPPER(suburb) = $2 AND (province IS NULL OR province != $1)`,
      [province, suburb.toUpperCase()]
    );
    if (result.rowCount && result.rowCount > 0) {
      updated += result.rowCount;
      console.log(`  ${suburb} → ${province} (${result.rowCount} rows)`);
    } else {
      skipped++;
    }
  }

  const unset = await client.query(
    `SELECT count(*)::int AS count FROM comparable_sales WHERE province IS NULL`
  );

  console.log(`\nDone. Updated ${updated} rows. ${unset.rows[0].count} rows still have no province.`);
  await client.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
