import { useEffect, useRef } from "react";
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';
import { formatter } from "../utils/formatting";

interface PDFReportProps {
  data: {
    address: string;
    longTermMonthly: number;
    shortTermMonthly: number;
    longTermAnnual: number;
    shortTermAnnual: number;
    shortTermAfterFees: number;
    breakEvenOccupancy: number;
    shortTermNightly: number;
    managementFee: number;
    annualOccupancy: number;
    bedrooms: string;
    bathrooms: string;
  };
  onClose: () => void;
}

export default function PDFReport({ data, onClose }: PDFReportProps) {
  const reportRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const generatePDF = () => {
      const doc = new jsPDF();

      // Add company logo and Proply branding
      doc.addImage("/proply-logo.png", "PNG", 160, 10, 40, 20);
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text("Powered by Proply", 160, 35);

      // Title
      doc.setFontSize(24);
      doc.setTextColor(0);
      doc.text("Property Analysis Report", 20, 30);

      // Property Details Section
      doc.setFontSize(16);
      doc.setTextColor(0, 121, 255);
      doc.text("Property Overview", 20, 50);

      autoTable(doc, {
        startY: 55,
        head: [["Property Details", "Specifications"]],
        body: [
          ["Address", data.address],
          ["Bedrooms", data.bedrooms],
          ["Bathrooms", data.bathrooms],
        ],
        theme: 'striped',
        styles: { fontSize: 12, cellPadding: 5 },
        headStyles: { fillColor: [0, 121, 255] }
      });

      // Revenue Analysis Section
      doc.setFontSize(16);
      doc.setTextColor(0, 121, 255);
      doc.text("Revenue Analysis", 20, doc.lastAutoTable.finalY + 20);

      autoTable(doc, {
        startY: doc.lastAutoTable.finalY + 25,
        head: [["Metric", "Value"]],
        body: [
          ["Average Nightly Rate", formatter.format(data.shortTermNightly)],
          ["Monthly Short-Term Revenue", formatter.format(data.shortTermMonthly)],
          ["Monthly Long-Term Revenue", formatter.format(data.longTermMonthly)],
          ["Annual Short-Term Revenue", formatter.format(data.shortTermAfterFees)],
          ["Annual Long-Term Revenue", formatter.format(data.longTermAnnual)],
          ["Current Occupancy Rate", `${data.annualOccupancy}%`],
          ["Management Fee", data.managementFee ? `${(data.managementFee * 100).toFixed(1)}%` : "N/A"],
        ],
        theme: 'striped',
        styles: { fontSize: 12, cellPadding: 5 },
        headStyles: { fillColor: [0, 121, 255] }
      });

      // Analysis Summary Section
      doc.setFontSize(16);
      doc.setTextColor(0, 121, 255);
      doc.text("Analysis Summary", 20, doc.lastAutoTable.finalY + 20);

      const summaryText = data.annualOccupancy > data.breakEvenOccupancy
        ? `At ${data.annualOccupancy}% projected occupancy, short-term rental strategy shows higher potential returns than long-term rental.`
        : `At ${data.annualOccupancy}% projected occupancy, long-term rental strategy may be more suitable for this property.`;

      doc.setFontSize(12);
      doc.setTextColor(60);
      const splitSummary = doc.splitTextToSize(summaryText, 170);
      doc.text(splitSummary, 20, doc.lastAutoTable.finalY + 30);

      const breakEvenText = `Break-even analysis shows that ${data.breakEvenOccupancy}% occupancy is needed to match long-term rental income.`;
      const splitBreakEven = doc.splitTextToSize(breakEvenText, 170);
      doc.text(splitBreakEven, 20, doc.lastAutoTable.finalY + 45);

      // Footer
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.setTextColor(150);
        // Add line above footer
        doc.line(20, 280, 190, 280);
        // Add footer text
        doc.text(`Report generated by Proply on ${new Date().toLocaleDateString()}`, 20, 285);
        doc.text(`Page ${i} of ${pageCount}`, 180, 285);
      }

      // Add disclaimer
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text("Disclaimer: All data is based on current market analysis and may vary. Proply assumes no liability for discrepancies.", 20, 290);

      // Save the PDF
      doc.save(`Property-Analysis-${data.address.split(",")[0]}.pdf`);
      onClose();
    };

    generatePDF();
  }, [data, onClose]);

  return <div ref={reportRef} style={{ display: 'none' }}></div>;
}