"use client"

import React, { useState } from "react"
import { Button } from "@/components/ui/button"
import { Download } from "lucide-react"
import { useToast } from "@/hooks/use-toast"

interface StaticPDFButtonProps {
  pdfPath: string
  className?: string
  children?: React.ReactNode
  propertyAddress?: string
}

export function StaticPDFButton({
  pdfPath,
  className,
  children,
  propertyAddress,
}: StaticPDFButtonProps) {
  const [isDownloading, setIsDownloading] = useState(false)
  const { toast } = useToast()
  
  // Function to trigger the PDF download directly
  const downloadPDF = () => {
    setIsDownloading(true)
    
    try {
      // Instead of using the static file with incorrect metadata,
      // we'll dynamically generate a PDF with proper title
      import('jspdf').then(module => {
        const jsPDF = module.default;
        const doc = new jsPDF({
          orientation: 'portrait',
          unit: 'mm',
          format: 'a4',
          putOnlyUsedFonts: true,
          title: 'Property Risk Assessment'
        });
        
        // Add title
        doc.setFontSize(22);
        doc.setTextColor(0, 0, 128);
        doc.text("Property Risk Assessment", 105, 20, { align: 'center' });
        
        // Add property address if available
        if (propertyAddress) {
          doc.setFontSize(16);
          doc.setTextColor(0, 0, 0);
          doc.text(`Property: ${propertyAddress}`, 105, 30, { align: 'center' });
        }
        
        // Add current date
        const currentDate = new Date().toLocaleDateString();
        doc.setFontSize(12);
        doc.text(`Report Date: ${currentDate}`, 105, 40, { align: 'center' });
        
        // Property Details Section
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text("Property Details", 20, 60);
        doc.setDrawColor(200, 200, 200);
        doc.line(20, 62, 190, 62);
        
        doc.setFontSize(12);
        doc.text("Address: 27 Leeuwen St, Cape Town City Centre, 8001", 20, 70);
        doc.text("Property Type: Apartment", 20, 78);
        doc.text("Size: 85 m²", 20, 86);
        doc.text("Bedrooms: 2", 20, 94);
        doc.text("Bathrooms: 2", 105, 94);
        doc.text("Parking: 1", 20, 102);
        doc.text("Condition: Excellent", 105, 102);
        
        // Risk Assessment Section
        doc.setFontSize(16);
        doc.text("Risk Assessment", 20, 120);
        doc.setDrawColor(200, 200, 200);
        doc.line(20, 122, 190, 122);
        
        doc.setFontSize(14);
        doc.text("Overall Risk Score: Moderate (58%)", 20, 130);
        
        // Risk Breakdown
        doc.setFontSize(14);
        doc.text("Risk Breakdown:", 20, 145);
        
        doc.setFontSize(12);
        doc.text("• Security: Medium (21/50)", 25, 155);
        doc.text("• Environmental: Medium (21/40)", 25, 163);
        doc.text("• Flood: Low (10/30)", 25, 171);
        doc.text("• Climate: Low (6/25)", 25, 179);
        doc.text("• Hail: Medium (10/30)", 25, 187);
        
        // Building Details Section
        doc.setFontSize(16);
        doc.text("Building Details", 20, 205);
        doc.setDrawColor(200, 200, 200);
        doc.line(20, 207, 190, 207);
        
        doc.setFontSize(12);
        doc.text("Roof Type: Concrete", 20, 215);
        doc.text("Wall Material: Brick", 105, 215);
        doc.text("Fire Retardant: Yes", 20, 223);
        doc.text("Lightning Conductor: No", 105, 223);
        
        // Security Details Section
        doc.setFontSize(16);
        doc.text("Security Details", 20, 240);
        doc.setDrawColor(200, 200, 200);
        doc.line(20, 242, 190, 242);
        
        doc.setFontSize(12);
        doc.text("Perimeter Wall: Brick wall higher than 1.8m", 20, 250);
        doc.text("Radio-linked Alarm: Yes", 20, 258);
        doc.text("Security Gates: Yes", 105, 258);
        doc.text("Burglar Bars: Yes", 20, 266);
        doc.text("Controlled Access: Yes", 105, 266);
        
        // Footer
        doc.setFontSize(9);
        doc.setTextColor(128, 128, 128);
        doc.text("Generated by Proply Risk Assessment Tool", 105, 285, { align: 'center' });
        
        // Save the PDF with a proper filename
        doc.save(`Property_Risk_Assessment${propertyAddress ? `_${propertyAddress.split(',')[0]}` : ''}.pdf`);
        
        toast({
          title: "Download Complete",
          description: "Your property risk assessment report has been downloaded.",
        });
        
        setIsDownloading(false);
      }).catch(err => {
        console.error('Error generating PDF:', err);
        toast({
          title: "Download Failed",
          description: "There was a problem creating the report. Please try again.",
          variant: "destructive",
        });
        setIsDownloading(false);
      });
    } catch (error) {
      console.error('Error in download process:', error);
      toast({
        title: "Download Failed",
        description: "There was a problem downloading the report. Please try again.",
        variant: "destructive",
      });
      setIsDownloading(false);
    }
  }

  return (
    <Button
      onClick={downloadPDF}
      disabled={isDownloading}
      className={className}
    >
      <Download className="mr-2 h-4 w-4" />
      {children || "Download PDF"}
    </Button>
  )
}